// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          int64
	UserID      int64
	NewsID      int64
	Name        string
	Description string
}

type News struct {
	ID          int64
	TagID       pgtype.Int8
	UserID      int64
	Title       string
	Descriprion string
	NameImage   string
}

type NewsTag struct {
	IDNews int64
	IDTag  int64
}

type Tag struct {
	ID   int64
	Name string
}

type User struct {
	ID         int64
	UserRoleID int64
	Name       string
	Password   string
}
