ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_fk0";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_fk0";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_fk1";

ALTER TABLE "news" DROP CONSTRAINT IF EXISTS "news_fk0";

ALTER TABLE "tags" DROP CONSTRAINT IF EXISTS "tags_fk0";
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "comments" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;
DROP TABLE IF EXISTS "news" CASCADE;
DROP TABLE IF EXISTS "news_tags" CASCADE;
DROP TABLE IF EXISTS "tags" CASCADE;